module c3_strnk_const
  use lib_const
  use c2_strnk_const, only: &
        STRNK_DIR_STRRANK     => DIR_STRRANK, &
        STRNK_DIR_ORG         => DIR_ORG    , &
        STRNK_DIR_PRD         => DIR_PRD    , &
        STRNK_DIR_STR         => DIR_STR    , &
        STRNK_NREGION         => NREGION    , &
        STRNK_REGION_HOKKAIDO => REGION_HOKKAIDO, &
        STRNK_REGION_HONSHU   => REGION_HONSHU  , &
        STRNK_REGION_SHIKOKU  => REGION_SHIKOKU , &
        STRNK_REGION_KYUSHU   => REGION_KYUSHU  , &
        STRNK_REGION_OKINAWA  => REGION_OKINAWA , &
        STRNK_REGION_ALL      => REGION_ALL, &
        STRNK_CLEN_NODEID => CLEN_NODEID, &
        STRNK_NODETYPE__SOURCE       => NODETYPE__SOURCE      , &
        STRNK_NODETYPE__OUTLET       => NODETYPE__OUTLET      , &
        STRNK_NODETYPE__INTERMEDIATE => NODETYPE__INTERMEDIATE, &
        STRNK_IDX_FIELD_RIVERNODE__WSCODE   => IDX_FIELD_RIVERNODE__WSCODE  , &
        STRNK_IDX_FIELD_RIVERNODE__NODEID   => IDX_FIELD_RIVERNODE__NODEID  , &
        STRNK_IDX_FIELD_RIVERNODE__ELV      => IDX_FIELD_RIVERNODE__ELV     , &
        STRNK_IDX_FIELD_RIVERNODE__ELVSRC   => IDX_FIELD_RIVERNODE__ELVSRC  , &
        STRNK_IDX_FIELD_RIVERNODE__DISTANCE => IDX_FIELD_RIVERNODE__DISTANCE, &
        STRNK_IDX_FIELD_RIVERNODE__MAXRANK  => IDX_FIELD_RIVERNODE__MAXRANK , &
        STRNK_IDX_FIELD_RIVERNODE__ENDPOINT => IDX_FIELD_RIVERNODE__ENDPOINT, &
        STRNK_IDX_FIELD_STREAM__WSCODE    => IDX_FIELD_STREAM__WSCODE   , &
        STRNK_IDX_FIELD_STREAM__RIVCODE   => IDX_FIELD_STREAM__RIVCODE  , &
        STRNK_IDX_FIELD_STREAM__RIVNAME   => IDX_FIELD_STREAM__RIVNAME  , &
        STRNK_IDX_FIELD_STREAM__SECTTYPE  => IDX_FIELD_STREAM__SECTTYPE , &
        STRNK_IDX_FIELD_STREAM__STRRANK   => IDX_FIELD_STREAM__STRRANK  , &
        STRNK_IDX_FIELD_STREAM__STRLENG   => IDX_FIELD_STREAM__STRLENG  , &
        STRNK_IDX_FIELD_STREAM__STRDZ     => IDX_FIELD_STREAM__STRDZ    , &
        STRNK_IDX_FIELD_STREAM__STRSLOPE  => IDX_FIELD_STREAM__STRSLOPE , &
        STRNK_IDX_FIELD_STREAM__MAXDIST   => IDX_FIELD_STREAM__MAXDIST  , &
        STRNK_IDX_FIELD_STREAM__NDUPSTR   => IDX_FIELD_STREAM__NDUPSTR  , &
        STRNK_IDX_FIELD_STREAM__NDDOWNSTR => IDX_FIELD_STREAM__NDDOWNSTR
  implicit none
end module c3_strnk_const
