
all:\
  make_cmn\
  make_make_basin\
  make_const_network\
  make_make_mesh_data

make_cmn:
	$(MAKE) -C cmn

make_make_basin:
	$(MAKE) -C make_basin

make_const_network:
	$(MAKE) -C const_network

make_make_mesh_data:
	$(MAKE) -C make_mesh_data


clean:\
  clean_cmn\
  clean_make_basin\
  clean_const_network\
  clean_make_mesh_data

clean_cmn:
	$(MAKE) -C cmn clean

clean_make_basin:
	$(MAKE) -C make_basin clean

clean_const_network:
	$(MAKE) -C const_network clean

clean_make_mesh_data:
	$(MAKE) -C make_mesh_data clean


